import {
  DESERT_RUN_WAYPOINTS,
  DESERT_RUN_CHECKPOINTS,
  FINISH_LINE,
  START_POSITION,
  START_ROTATION_Y,
} from './checkpoints'

export const NEON_CITY_WAYPOINTS = DESERT_RUN_WAYPOINTS
export const NEON_CITY_CHECKPOINTS = DESERT_RUN_CHECKPOINTS
export const NEON_FINISH_LINE = FINISH_LINE
export const NEON_START_POSITION = START_POSITION
export const NEON_START_ROTATION_Y = START_ROTATION_Y